name: CI/CD React a S3

on:
  push:
    branches:
      - main # o master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar la aplicación React
        run: npm run build

  deploy:
      runs-on: ubuntu-latest
      needs: build # Asegura que el despliegue se ejecute solo si la compilación fue exitosa
      steps:
        - name: Checkout del repositorio
          uses: actions/checkout@v4

        - name: Configurar credenciales de AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2 # o la región de tu bucket

        - name: Sincronizar archivos a S3
          run: aws s3 sync ./build/ s3://mainprocedure.com --delete

        - name: Invalidar caché de CloudFront
          run: |
            aws cloudfront create-invalidation --distribution-id TU_DISTRIBUTION_ID --paths "/*"